import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { 
  ShieldAlert, Upload, Search, FileText, CheckCircle2, 
  ArrowRight, Zap, Lock, Database, LayoutTemplate, 
  Eye, RefreshCw, BarChart2, Users, AlertTriangle, Sparkles,
  Video
} from 'lucide-react';
import GlassCard from '../../components/GlassCard';
import { useAuth } from '../../context/AuthContext';

const LandingPage = () => {
  const { user } = useAuth();
  const [activeExplainTab, setActiveExplainTab] = useState('image');

  // How It Works Steps
  const steps = [
    { num: '01', title: 'Upload', desc: 'Upload your files (images, videos, audio, or text) directly into the dashboard.', icon: Upload, color: 'text-sky-400 border-sky-500/20 bg-sky-500/5' },
    { num: '02', title: 'Analyze', desc: 'Our system analyzes the media to search for signs of AI generation or editing.', icon: Search, color: 'text-indigo-400 border-indigo-500/20 bg-indigo-500/5' },
    { num: '03', title: 'Explain', desc: 'View easy-to-understand visual heatmaps and explanations highlighting exactly where edits were made.', icon: Sparkles, color: 'text-fuchsia-400 border-fuchsia-500/20 bg-fuchsia-500/5' },
    { num: '04', title: 'Verify', desc: 'Download verification reports showing the final authenticity score and scan history.', icon: CheckCircle2, color: 'text-emerald-400 border-emerald-500/20 bg-emerald-500/5' },
  ];

  // Media Cards
  const mediaTypes = [
    { title: 'Image Verification', path: '/image', desc: 'Detect photoshop edits, cropped or spliced images, and AI-generated content (DALL-E, Midjourney).', detail: 'Analyzes pixel noise patterns and image compression levels.', icon: Eye, color: 'from-sky-500/20 to-blue-600/20 text-sky-400' },
    { title: 'Video Verification', path: '/video', desc: 'Identify deepfakes, face swaps, and video frames edited or generated by AI.', detail: 'Scans face structures, movement, and lighting patterns frame-by-frame.', icon: Search, color: 'from-indigo-500/20 to-purple-600/20 text-indigo-400' },
    { title: 'Audio Verification', path: '/audio', desc: 'Verify if voice recordings are authentic or cloned by AI voice generators.', detail: 'Analyzes sound waves, voice frequencies, and speech patterns.', icon: Zap, color: 'from-fuchsia-500/20 to-pink-600/20 text-fuchsia-400' },
    { title: 'Text Verification', path: '/text', desc: 'Scan articles and documents to check if the writing is AI-generated (like ChatGPT).', detail: 'Examines writing structure, word choices, and predictability scores.', icon: FileText, color: 'from-emerald-500/20 to-teal-600/20 text-emerald-400' },
  ];

  // Features List
  const features = [
    { title: 'Multi-Modal Analysis', desc: 'Verify images, videos, audio clips, and text documents all on one single platform.', icon: ShieldAlert },
    { title: 'Explainable AI (XAI)', desc: 'See visual heatmaps and text explanations instead of just a generic "Real" or "Fake" result.', icon: Sparkles },
    { title: 'Real-Time Verification', desc: 'Get instant results in seconds with optimized, high-performance scanning.', icon: Zap },
    { title: 'Secure Authentication', desc: 'Your private file uploads are secure and accessible only during your session.', icon: Lock },
    { title: 'History Tracking', desc: 'Save your previous scans to easily search, filter, and compare results over time.', icon: Database },
    { title: 'Interactive Dashboard', desc: 'A clean, interactive user interface built for easy media analysis and verification.', icon: LayoutTemplate },
  ];

  // Team Members
  const team = [
    { 
      name: 'Namrah Arfin', 
      role: 'Project Lead & System Architect', 
      specialty: 'UI/UX Design & Integration Engineering', 
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Namrah',
      github: 'https://github.com/NamrahArfin'
    },
    { 
      name: 'Laxmi Yadav', 
      role: 'Verification Module Developer', 
      specialty: 'Image & Video Analysis Forensic Pipeline', 
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Laxmi',
      github: 'https://github.com/Laxmi1902'
    },
    { 
      name: 'Raj Nandini Dubey', 
      role: 'Verification Module Developer', 
      specialty: 'Audio & Text Processing NLP Engines', 
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=RajNandini',
      github: 'https://github.com/RajNandini77'
    },
  ];

  return (
    <div className="space-y-24 pb-16">
      
      {/* 1. HERO SECTION */}
      <section className="relative pt-12 md:pt-20 max-w-7xl mx-auto px-6 text-center space-y-8">
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-black font-orbitron tracking-tight leading-tight max-w-5xl mx-auto">
          Explainable AI-Driven <br className="hidden sm:inline" />
          <span className="bg-gradient-to-r from-brand-blue via-brand-purple to-brand-purple bg-clip-text text-transparent bg-size-200">
            Real-Time Multi-Modal
          </span> <br className="hidden md:inline" />
          Digital Media Verification System
        </h1>

        <p className="text-sm md:text-base text-slate-500 dark:text-slate-400 max-w-2xl mx-auto leading-relaxed font-medium">
          RealVeritas AI helps you check if your images, videos, audio, and text files are real or manipulated, providing clear confidence scores and detailed visual explanations.
        </p>

        <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
          <Link
            to={user ? '/dashboard' : '/signup'}
            className="px-8 py-3.5 rounded-xl font-bold font-orbitron text-sm bg-gradient-to-r from-brand-blue to-brand-purple text-white shadow-lg shadow-brand-blue/20 hover:shadow-[0_0_25px_rgba(14,165,233,0.5)] hover:scale-[1.02] active:scale-95 transition-all duration-200 cursor-pointer flex items-center gap-2 group"
          >
            <span>Get Started</span>
            <ArrowRight className="h-4.5 w-4.5 group-hover:translate-x-1 transition-transform" />
          </Link>
          <a
            href="#how-it-works"
            className="px-8 py-3.5 rounded-xl font-bold font-orbitron text-sm border border-slate-300 dark:border-white/10 text-slate-700 dark:text-slate-200 bg-white/40 dark:bg-black/20 hover:bg-white/60 dark:hover:bg-black/40 hover:scale-[1.02] transition-all duration-200"
          >
            Learn More
          </a>
        </div>


      </section>

      {/* 2. HOW IT WORKS */}
      <section id="how-it-works" className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-2xl md:text-3xl font-extrabold font-orbitron tracking-wider">
            How It Works
          </h2>
          <p className="text-xs md:text-sm text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
            From single files to full reports, Veritas AI simplifies complex forensic calculations into a clear 4-step trust pipeline.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {steps.map((step, idx) => {
            const Icon = step.icon;
            return (
              <GlassCard key={idx} className="relative overflow-hidden group">
                <span className="absolute top-2 right-4 text-5xl font-black font-orbitron text-slate-300/20 dark:text-slate-700/15 select-none">
                  {step.num}
                </span>
                <div className="space-y-4">
                  <div className={`h-11 w-11 rounded-xl border flex items-center justify-center ${step.color}`}>
                    <Icon className="h-5.5 w-5.5" />
                  </div>
                  <h3 className="font-orbitron font-bold text-base text-slate-800 dark:text-slate-100">
                    {step.title}
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                    {step.desc}
                  </p>
                </div>
              </GlassCard>
            );
          })}
        </div>
      </section>

      {/* 3. SUPPORTED MEDIA TYPES */}
      <section id="supported" className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-2xl md:text-3xl font-extrabold font-orbitron tracking-wider">
            Supported Media Verification
          </h2>
          <p className="text-xs md:text-sm text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
            We isolate anomalies and verify content across four distinct channels using specialised neural networks.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {mediaTypes.map((item, idx) => {
            const Icon = item.icon;
            return (
              <GlassCard 
                key={idx} 
                hoverGlow={true}
                className="flex flex-col justify-between h-64 border-l-4 border-l-brand-blue group"
              >
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="font-orbitron font-extrabold text-base text-slate-800 dark:text-slate-100 group-hover:text-brand-blue transition-colors">
                      {item.title}
                    </h3>
                    <div className="p-2.5 rounded-xl bg-slate-100 dark:bg-slate-800/80 text-slate-600 dark:text-slate-300">
                      <Icon className="h-5 w-5" />
                    </div>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed font-medium">
                    {item.desc}
                  </p>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500 leading-relaxed">
                    {item.detail}
                  </p>
                </div>
                
                <div className="pt-4 border-t border-black/5 dark:border-white/5 flex items-center justify-between">
                  <span className="text-[10px] font-orbitron font-bold text-slate-400 uppercase tracking-widest">
                    Active Module: V1.4
                  </span>
                  <Link 
                    to={user ? item.path : '/login'} 
                    className="text-xs font-bold font-orbitron text-brand-blue hover:text-brand-purple flex items-center gap-1.5 transition-colors cursor-pointer"
                  >
                    <span>Verify Now</span>
                    <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-1 transition-transform" />
                  </Link>
                </div>
              </GlassCard>
            );
          })}
        </div>
      </section>

      {/* 4. FEATURES SECTION */}
      <section className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-2xl md:text-3xl font-extrabold font-orbitron tracking-wider">
            Platform Capabilities
          </h2>
          <p className="text-xs md:text-sm text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
            RealVeritas AI equips your team with production-grade forensic tooling designed for fast, accurate workflows.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat, idx) => {
            const Icon = feat.icon;
            return (
              <div 
                key={idx}
                className="p-6 rounded-2xl border border-black/5 dark:border-white/5 bg-slate-100/30 dark:bg-slate-900/10 hover:border-brand-purple/20 transition-all duration-300 hover:scale-[1.01]"
              >
                <div className="flex gap-4">
                  <div className="p-2.5 rounded-xl bg-gradient-to-tr from-brand-blue/10 to-brand-purple/10 text-brand-purple shrink-0">
                    <Icon className="h-5.5 w-5.5" />
                  </div>
                  <div className="space-y-1">
                    <h3 className="font-bold text-slate-800 dark:text-slate-100 text-sm font-orbitron">
                      {feat.title}
                    </h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium">
                      {feat.desc}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* 5. EXPLAINABLE AI SECTION */}
      <section className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-2xl md:text-3xl font-extrabold font-orbitron tracking-wider">
            Explainable AI Visualizations
          </h2>
          <p className="text-xs md:text-sm text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
            We reject the black-box model. RealVeritas provides deep visual insights showing exactly where manipulations are flagged.
          </p>
        </div>

        <GlassCard className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch p-2 sm:p-6 overflow-hidden">
          {/* Left: Tab selection and descriptions */}
          <div className="lg:col-span-5 flex flex-col justify-between py-4 pl-4 space-y-6">
            <div className="space-y-4">
              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-2 gap-2">
                {['image', 'video', 'audio', 'text'].map((tab) => (
                  <button
                    key={tab}
                    onClick={() => setActiveExplainTab(tab)}
                    className={`px-3 py-2.5 rounded-xl text-[10px] sm:text-xs font-bold font-orbitron uppercase tracking-wider transition-all cursor-pointer text-center w-full ${
                      activeExplainTab === tab
                        ? 'bg-gradient-to-r from-brand-blue to-brand-purple text-white shadow-md'
                        : 'bg-black/5 dark:bg-white/5 text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200'
                    }`}
                  >
                    {tab} E.X.A.I.
                  </button>
                ))}
              </div>

              <div className="space-y-3 pt-2">
                <h3 className="font-orbitron font-extrabold text-xl text-slate-800 dark:text-slate-100">
                  {activeExplainTab === 'image' && 'Spatial Manipulation Heatmaps'}
                  {activeExplainTab === 'video' && 'Temporal Frame Consistency'}
                  {activeExplainTab === 'audio' && 'Frequency Phase Spectrograms'}
                  {activeExplainTab === 'text' && 'NLP Syntax Burstiness Markers'}
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium">
                  {activeExplainTab === 'image' && 'Image analysis maps fine noise fields across pixel blocks. Splice zones reveal discrete deviations in noise alignment, colored in red/yellow overlay heatmaps.'}
                  {activeExplainTab === 'video' && 'Video parsing tracks motion vector streams and facial landmark meshes. Frame-by-frame anomalies reveal face-swaps, deepfake generation boundaries, and optical flow discrepancies.'}
                  {activeExplainTab === 'audio' && 'Spectrogram panels isolate voice harmonics. AI voice cloning leaves phase cancellations at specific high-frequency filters, flagged instantly by spectrogram scans.'}
                  {activeExplainTab === 'text' && 'ChatGPT-generated inputs have extremely uniform perplexity structures. Our NLP system highlights paragraphs showing low vocabulary burstiness.'}
                </p>
              </div>
            </div>

            {/* Explainable Stats Block */}
            <div className="border-t border-black/10 dark:border-white/10 pt-4 grid grid-cols-2 gap-4">
              <div>
                <p className="text-[10px] text-slate-400 font-semibold font-orbitron uppercase">AI Decision Confidence</p>
                <p className="text-xl font-bold font-orbitron text-brand-blue">98.4% Accuracy</p>
              </div>
              <div>
                <p className="text-[10px] text-slate-400 font-semibold font-orbitron uppercase">Reasoning Clarity Index</p>
                <p className="text-xl font-bold font-orbitron text-brand-purple">Explainable (Level 4)</p>
              </div>
            </div>
          </div>

          {/* Right: Visual Showcase Panel */}
          <div className="lg:col-span-7 bg-slate-900 rounded-xl overflow-hidden min-h-[300px] flex flex-col justify-between border border-white/5 relative p-4 text-left">
            {/* Visual Screen based on active tab */}
            {activeExplainTab === 'image' && (
              <div className="relative flex-1 flex flex-col justify-center items-center h-full">
                <div className="absolute top-2 left-2 z-20 flex gap-2">
                  <span className="px-2 py-0.5 rounded bg-red-500/10 text-red-400 border border-red-500/20 text-[9px] font-orbitron font-bold">MANIPULATION REGION</span>
                  <span className="px-2 py-0.5 rounded bg-black/50 text-white text-[9px] font-orbitron font-bold">ELA MODE</span>
                </div>
                {/* Fake Image Container with ELA overlay */}
                <div className="relative w-72 h-48 rounded-lg overflow-hidden border border-white/10 bg-slate-800 shadow-xl flex items-center justify-center">
                  <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_40%,rgba(239,68,68,0.5),rgba(239,68,68,0.1)_20%,transparent_50%)]" />
                  <div className="absolute top-[40%] left-[70%] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center gap-1 z-10">
                    <span className="text-[9px] font-mono text-white bg-red-500/80 px-1 py-0.5 rounded shadow">Splice anomaly (74%)</span>
                    <div className="w-16 h-16 rounded-full border-2 border-dashed border-red-500 animate-ping absolute -top-4" />
                  </div>
                  {/* Grid Lines inside mockup */}
                  <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:16px_16px]" />
                  <div className="text-center space-y-1 select-none">
                    <ShieldAlert className="h-8 w-8 text-slate-500 mx-auto" />
                    <p className="text-[9px] font-mono text-slate-400">cfa_noise_field_v1.png</p>
                  </div>
                </div>
              </div>
            )}

            {activeExplainTab === 'video' && (
              <div className="relative flex-1 flex flex-col justify-center items-center h-full">
                <div className="absolute top-2 left-2 z-20 flex gap-2">
                  <span className="px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 text-[9px] font-orbitron font-bold">FACIAL MESH VECTOR</span>
                  <span className="px-2 py-0.5 rounded bg-black/50 text-white text-[9px] font-orbitron font-bold">OPTICAL FLOW</span>
                </div>
                {/* Fake Video Frame with Face Mesh Overlay */}
                <div className="relative w-72 h-48 rounded-lg overflow-hidden border border-white/10 bg-slate-800 shadow-xl flex items-center justify-center">
                  <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(99,102,241,0.2),transparent_60%)]" />
                  
                  {/* Face mesh simulation SVG */}
                  <svg className="absolute inset-0 w-full h-full opacity-60 pointer-events-none" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <path d="M50 35 L42 45 L50 55 L58 45 Z" fill="none" stroke="#6366f1" strokeWidth="0.5" />
                    <path d="M42 45 L35 48 L40 58 L50 55" fill="none" stroke="#6366f1" strokeWidth="0.5" />
                    <path d="M58 45 L65 48 L60 58 L50 55" fill="none" stroke="#6366f1" strokeWidth="0.5" />
                    <circle cx="50" cy="35" r="1.5" fill="#6366f1" />
                    <circle cx="42" cy="45" r="1.5" fill="#6366f1" />
                    <circle cx="58" cy="45" r="1.5" fill="#f43f5e" className="animate-ping" />
                    <circle cx="58" cy="45" r="1.5" fill="#f43f5e" />
                    <circle cx="50" cy="55" r="1.5" fill="#6366f1" />
                    <circle cx="35" cy="48" r="1.5" fill="#6366f1" />
                    <circle cx="65" cy="48" r="1.5" fill="#6366f1" />
                    <circle cx="40" cy="58" r="1.5" fill="#6366f1" />
                    <circle cx="60" cy="58" r="1.5" fill="#6366f1" />
                  </svg>

                  <div className="absolute top-[40%] left-[58%] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center gap-1 z-10">
                    <span className="text-[9px] font-mono text-white bg-red-500/80 px-1 py-0.5 rounded shadow">Mesh Jitter (91%)</span>
                    <div className="w-12 h-12 rounded-full border border-dashed border-red-500 animate-pulse absolute -top-3" />
                  </div>

                  {/* Grid Lines inside mockup */}
                  <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:16px_16px]" />
                  <div className="text-center space-y-1 select-none">
                    <Video className="h-8 w-8 text-slate-500 mx-auto" />
                    <p className="text-[9px] font-mono text-slate-400">temporal_stream_v4.mp4</p>
                  </div>
                </div>
              </div>
            )}

            {activeExplainTab === 'audio' && (
              <div className="relative flex-1 flex flex-col justify-center h-full">
                <div className="absolute top-2 left-2 z-20 flex gap-2">
                  <span className="px-2 py-0.5 rounded bg-fuchsia-500/10 text-fuchsia-400 border border-fuchsia-500/20 text-[9px] font-orbitron font-bold">SYNTHESIS HARMONICS</span>
                </div>
                {/* Fake Audio Spectrogram representation */}
                <div className="w-full h-44 rounded-lg overflow-hidden border border-white/10 bg-slate-950 p-2 flex flex-col justify-between relative shadow-xl">
                  <div className="flex-1 flex items-end gap-[2px]">
                    {[60, 45, 80, 55, 95, 75, 40, 25, 90, 85, 12, 45, 92, 105, 115, 60, 30, 75, 88, 98, 44, 25, 65, 82, 110, 70, 45, 85, 60, 40, 95, 80, 45, 20, 70].map((h, i) => (
                      <div 
                        key={i} 
                        className={`flex-1 rounded-t-sm transition-all duration-300 ${
                          h > 90 
                            ? 'bg-gradient-to-t from-fuchsia-500 to-red-500 animate-pulse' 
                            : 'bg-gradient-to-t from-brand-blue/30 to-brand-blue'
                        }`} 
                        style={{ height: `${h}%` }} 
                      />
                    ))}
                  </div>
                  <div className="flex justify-between text-[8px] font-mono text-slate-500 border-t border-white/5 pt-1 mt-1">
                    <span>100 Hz</span>
                    <span>1000 Hz</span>
                    <span className="text-fuchsia-400 font-bold">VOC-CANCEL BLOCK</span>
                    <span>8000 Hz</span>
                  </div>
                </div>
              </div>
            )}

            {activeExplainTab === 'text' && (
              <div className="relative flex-1 flex flex-col justify-center h-full">
                <div className="absolute top-2 left-2 z-20 flex gap-2">
                  <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-[9px] font-orbitron font-bold">GPT PATTERN PARSER</span>
                </div>
                <div className="w-full h-44 rounded-lg overflow-hidden border border-white/10 bg-slate-950 p-4 text-[10px] font-mono text-slate-300 leading-relaxed shadow-xl overflow-y-auto">
                  <p>
                    The integration of smart grids <span className="bg-emerald-500/20 border-b border-emerald-500 text-emerald-400 px-0.5 py-0.5 rounded select-none cursor-help" title="Burstiness deviation: 94%">represents a key technical lever</span> for renewable energy adoption. <span className="bg-purple-500/20 border-b border-brand-purple text-purple-300 px-0.5 py-0.5 rounded select-none cursor-help" title="Perplexity match: GPT-4 (92%)">Furthermore, it is important to consider</span> that these architectures optimize distributions. In conclusion, the adoption remains vital.
                  </p>
                </div>
              </div>
            )}

            {/* Bottom reasoning log */}
            <div className="border-t border-white/5 pt-2 flex items-center justify-between text-[10px] text-slate-500 font-mono">
              <span>
                {activeExplainTab === 'image' && 'Reasoning: anomaly detected at block index A4'}
                {activeExplainTab === 'video' && 'Reasoning: temporal landmark inconsistency detected in frame 242'}
                {activeExplainTab === 'audio' && 'Reasoning: synthetic phase cancellation matched at sub-filter 8kHz'}
                {activeExplainTab === 'text' && 'Reasoning: perplexity uniform distribution pattern matches GPT generator signature'}
              </span>
              <span className="text-brand-purple flex items-center gap-1 cursor-pointer">
                <RefreshCw className="h-3 w-3 animate-[spin_4s_linear_infinite]" /> Refresh Engine
              </span>
            </div>
          </div>
        </GlassCard>
      </section>

      {/* 6. TEAM SECTION */}
      <section className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-2xl md:text-3xl font-extrabold font-orbitron tracking-wider">
            Research & Platform Team
          </h2>
          <p className="text-xs md:text-sm text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
            Pioneering transparency in digital forensics. Our researchers bridge the gap between complex network theory and verification UX.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {team.map((member, idx) => (
            <GlassCard 
              key={idx} 
              hoverGlow={true}
              onClick={() => window.open(member.github, '_blank')}
              className="text-center space-y-4 group cursor-pointer relative"
            >
              {/* GitHub Link Indicator Badge */}
              <div className="absolute top-3 right-4 opacity-40 group-hover:opacity-100 transition-opacity">
                <svg
                  className="h-4.5 w-4.5 text-slate-400 dark:text-slate-500 group-hover:text-brand-blue transition-colors"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
                  <path d="M9 18c-4.51 2-5-2-7-2" />
                </svg>
              </div>

              <div className="relative inline-block">
                <div className="absolute inset-0 bg-gradient-to-tr from-brand-blue to-brand-purple rounded-full blur-[10px] opacity-20 group-hover:opacity-40 transition-opacity" />
                <img 
                  src={member.avatar} 
                  alt={member.name} 
                  className="h-20 w-20 rounded-full border border-black/10 dark:border-white/20 bg-slate-100 dark:bg-slate-900 mx-auto relative z-10 group-hover:scale-105 transition-transform"
                />
              </div>
              <div className="space-y-1">
                <h3 className="font-bold text-slate-800 dark:text-slate-100 text-sm font-orbitron group-hover:text-brand-blue transition-colors">
                  {member.name}
                </h3>
                <p className="text-xs text-brand-blue font-semibold">{member.role}</p>
                <p className="text-[10px] text-slate-400 dark:text-slate-500 leading-tight font-medium">
                  {member.specialty}
                </p>
              </div>
            </GlassCard>
          ))}
        </div>
      </section>

    </div>
  );
};

export default LandingPage;
